### Gaussian example

In [ ]:
import numpy as np
from sklearn.utils import check_random_state
random_state = check_random_state(1)
data0 = random_state.normal(0, 1, 100*30).reshape(100, 30)
data = np.array(data0)

### KNN 

In [29]:
import numpy as np
from sklearn.neighbors import KDTree
import sklearn.datasets
import sklearn.model_selection

# Load iris dataset
iris = sklearn.datasets.load_iris()
train, _, _, _ = sklearn.model_selection.train_test_split(iris.data, iris.target, train_size=0.80)

# Calculate Euclidean distance between train[0] and train[102]
distance = np.linalg.norm(train[0] - train[102])
print("Euclidean Distance:", distance)

# Build KDTree
kdt = KDTree(train, leaf_size=30, metric='euclidean')

data_row = train[0]
# Function to find top 10 nearest neighbors to train[i]
def find_top_10_neighbors(i):
    distances, indices = kdt.query(train[i].reshape(1, -1), k=11)  # k=11 to include the point itself
    return train[indices[0][1:]]  # Exclude the first index as it's the point itself

# Example usage
i = 0  # Index of the data point
top_10_neighbors = find_top_10_neighbors(i)
print("Top 10 nearest neighbor arrays to train[{}]:\n{}".format(i, top_10_neighbors))
print(kdt.query(data_row.reshape(1, -1), k=11))


Euclidean Distance: 1.4317821063276355
Top 10 nearest neighbor arrays to train[0]:
[[6.3 3.4 5.6 2.4]
 [6.4 3.2 5.3 2.3]
 [6.5 3.2 5.1 2. ]
 [6.5 3.  5.2 2. ]
 [6.7 3.1 5.6 2.4]
 [6.4 3.1 5.5 1.8]
 [6.7 3.3 5.7 2.1]
 [6.7 3.3 5.7 2.5]
 [6.5 3.  5.8 2.2]
 [6.3 3.3 6.  2.5]]
(array([[0.        , 0.24494897, 0.3       , 0.55677644, 0.6164414 ,
        0.6244998 , 0.6244998 , 0.6244998 , 0.6244998 , 0.64807407,
        0.64807407]]), array([[  0,  26,  77,  75,  25,   2,  56,  55, 100,  34,  39]]))
